default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: message_me_development
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: localhost
  port: 5432
test:
  <<: *default
  database: message_me_test
# there is no productin env yet
# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
#   database: message_me_production
#   username: message_me
#   password: <%= ENV['DATABASE_PASSWORD'] %>
